### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by joshin-run** [fee-slc-2017/Group-Project-One#3]

**Comment by T-dex** [comment]
We are using the flexbox site as a wireframe and inserting basic elements to understand location of boxes.

**Comment by tylerbyte** [comment]
We will create links and buttons. Logo will be represented as a custom made logo (designed by Josh and Rob). Buttons will be listed left to right( Vision, Design Team, Projects, Contact) aligned horizontally. The nav bar 'look' will be thin and sleek.

**Comment by T-dex** [comment]
Cool thanks

**Comment by tylerbyte** [comment]
We're going to change the nav bar to a fixed position. {tuningmind, cheezeypotatoes, Dex, and tylerbyte}

**Comment by tylerbyte** [comment]
We made the following changes on the navbar branch: 

- Removed banner image

- added 'nowrap' to menu container

- Added/styled four nav buttons

**Comment by cheezeypotatoes** [comment]
this issue has been closed vav bar has been created
